<?php
$title = "Education";
include("header.php");
?>
<h1>Work</h1>
<h2>Employment</h2>
<p>In July 2026, I will be an Undergraduate Program Assistant at the <?php mention("https://summeracademy.ics.uci.edu/","UCI Information and Computer Sciences Summer Academy"); ?>, for $16.90/hr, with a team of about 30 people. The Summer Academy, affiliated with the <?php mention("https://oai.ics.uci.edu/","Stacey Nicholas Office of Outreach, Access, and Inclusion"); ?>, is an introductory summer course program for high school students interested in computer science. I will be supporting <?php mention($sites["michael"],"Professor Michael Shindler"); ?>'s courses in AI/ML and cryptography.</p>
<p>Since January 2026, I volunteer as a designer and website developer for <?php mention("https://www.sonandosinmiedo.org","Soñando Sin Miedo"); ?>, a nonprofit organization dedicated to supporting the college and career development of first-generation or low-income high school students, based in Southern California. I was also a general volunteer for SSM's first Professional Development Fair.</p>
<p>Since Fall 2025, I am a drop-in tutor at the <?php mention("https://tutoring.ics.uci.edu/group-tutoring/","UCI Information and Computer Sciences Tutoring Center"); ?>, for $22.15/hr, with a team of about ten people. I am responsible for tutoring students in lower-division Assembly, C, C++, Python, data structures, boolean logic and discrete structures, discrete mathematics, statistics, computer architecture, and operating systems. I am also responsible for tracking which students I tutor and for how long, for purposes of securing funding for the next fiscal year.</p>
<p>Since Summer 2025, I am an undergraduate research assistant for <?php mention($sites["michael"],"Professor Michael Shindler"); ?> at UCI, with some time volunteered and some time compensated with academic credits, with a team of about 15 people, including graduate students and undergraduate students. I am responsible, with Julia Nguyen, for leading a study on student experiences and persistence. I also contribute to studies on active learning.</p>
<p>In Spring 2024, I was a learning assistant for boolean logic and discrete structures taught by Professor Irene Gassko at UCI, with time compensated with academic credits, with a team of about 20 people, including graduate student TAs, undergraduate graders, and undergraduate learning assistants. In Winter 2025 and Winter 2026, I was the lead learning assistant for discrete mathematics taught by Professor Gassko, with teams of similar size but without graders in 2026. For these courses, I was responsible for supporting around 300 students each term in flipped-classroom activities, hosting weekly study hall sessions, meeting weekly to discuss the course content and structure, and proctoring exams. As a lead, I hosted some of our weekly meetings. In Spring 2026, I am a learning assistant for theory of computation taught by <?php mention($sites["michael"],"Professor Michael Shindler"); ?>.</p>
<?php
include("footer.php");
?>